version: 1.0.{build}

configuration: Release
platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
before_build:
- nuget restore "src\TestingCI.sln"

build:
  project: src\TestingCI.sln
  verbosity: minimal

after_build:
- md "src\build\nuget"
- nuget pack "src\nuget\TestingCI.WhatTheLibrary.nuspec" -version "%APPVEYOR_BUILD_VERSION%" -properties "configuration=%CONFIGURATION%" -OutputDirectory "src\build\nuget"

artifacts:
  - path: src\build\{configuration}
  - path: src\build\nuget\*.nupkg