# configuration for "master" branch
# build in Release mode and deploy to NuGet.org
- version: 1.1.1

  branches:
    only:
    - master
  
  configuration: Release
  platform: Any CPU
  
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    
  before_build:
  - nuget restore "src\TestingCI.sln"
  
  build:
    project: src\TestingCI.sln
    verbosity: minimal
  
  after_build:
  - md "src\build\nuget"
  - nuget pack "src\nuget\TestingCI.WhatTheLibrary.nuspec" -version "%APPVEYOR_BUILD_VERSION%" -properties "configuration=%CONFIGURATION%" -OutputDirectory "src\build\nuget"
  
  artifacts:
    - path: src\build\{configuration}
    - path: src\build\nuget\*.nupkg

  deploy:
  - provider: Environment
    name: MyGet Private TestingCI (micdenny)
    on:
      branch: master

# configuration for "development" branch
# build in Debug mode and deploy to MyGet.org as pre-release
- version: 1.1.1-alpha1-{build}

  branches:
    only:
    - develop
  
  configuration: Debug
  platform: Any CPU
  
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    
  before_build:
  - nuget restore "src\TestingCI.sln"
  
  build:
    project: src\TestingCI.sln
    verbosity: minimal
  
  after_build:
  - md "src\build\nuget"
  - nuget pack "src\nuget\TestingCI.WhatTheLibrary.nuspec" -version "%APPVEYOR_BUILD_VERSION%" -properties "configuration=%CONFIGURATION%" -OutputDirectory "src\build\nuget"
  
  artifacts:
    - path: src\build\{configuration}
    - path: src\build\nuget\*.nupkg

  deploy:
  - provider: Environment
    name: MyGet Private TestingCI (micdenny)
    on:
      branch: develop

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
- configuration: Debug
  platform: Any CPU

  before_build:
  - nuget restore "src\TestingCI.sln"
  
  build:
    project: src\TestingCI.sln
    verbosity: minimal